name: sokoban
version: 0.1.0
author: Nick Linker <nlinker@gmail.com>
maintainer: Nick Linker <nlinker@gmail.com>

# -ddump-splices to see TH generation
# -ddump-ds to desugar
ghc-options: -threaded -Wall -fno-warn-name-shadowing

github: nlinker/sokoban-hs

library:
  source-dirs:
    - src
  exposed-modules:
    - Sokoban.Console
    - Sokoban.Data
    - Sokoban.Debug
    - Sokoban.Example
    - Sokoban.Keys
    - Sokoban.Level
    - Sokoban.Model
    - Sokoban.Parser
    - Sokoban.Resources
    - Sokoban.Solver
    - Helper
  other-modules:
    - Paths_sokoban

executables:
  sokoban:
    main: Main.hs
    source-dirs:
      - exe
    dependencies:
      - sokoban

tests:
  unit:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - sokoban
      - criterion
      - hspec
      - mwc-random
      - QuickCheck
      - quickcheck-instances

dependencies:
  - ansi-terminal
  - async
  - base
  - bytestring
  - Cabal
  - deepseq
  - extra
  - hashable
  - impure-containers
  - lens
  - MonadRandom
  - mtl
  - parallel
  - primitive
  - qm-interpolated-string
  - reactive-banana
  - stm
  - STMonadTrans
  - template-haskell
  - transformers
  - text
  - text-builder
  - unordered-containers
  - vector
  - word8
