name: sokoban
version: 0.1.0
# -ddump-splices to see TH generation
# -ddump-ds to desugar
ghc-options: -threaded -Wall -fno-warn-name-shadowing

executables:
  sokoban:
    main: Main.hs
    source-dirs:
      - app
    dependencies:
      - sokoban

library:
  source-dirs:
    - src
  other-modules:
    - Paths_sokoban

tests:
  unit:
    main: UnitTests.hs
    source-dirs:
      - test
    dependencies:
      - sokoban
      - hspec

dependencies:
    - ansi-terminal
    - base
    - bytestring
    - Cabal
    - extra
    - hashable
    - MonadRandom
    - mtl
    - rainbox
    - template-haskell
    - transformers
    - text
    - unordered-containers
    - word8
    - vector
    - lens

